name: JapAura
description: "Radha Nam Jap Counter App â€“ JapAura"

# Prevent accidental publish to pub.dev
publish_to: 'none'

# Version and build number
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  vibration: ^3.1.3
  audioplayers: ^6.5.1
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1   # Added for app logo

flutter:
  uses-material-design: true

  assets:
    - assets/images/radha.png
    - assets/images/shiva.png
    - assets/images/krishna.png
    - assets/images/ganesha.png
    - assets/images/hanuman.png
    - assets/images/gayatri.png
    - assets/images/ram.png
    - assets/audio/bell.mp3
    - assets/logo.png

# Launcher icon configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"   # path to your logo
  adaptive_icon_background: "#FFA500"  # Orange background
  adaptive_icon_foreground: "assets/logo.png"
